version: '3.8'
services:
  reverse_proxy:
    image: traefik
    container_name: reverse_proxy
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  web_static:
    build: ../apache-php-image/
    labels:
      - traefik.http.routers.web_static.rule=Host("demo.api.ch")
      - traefik.http.services.web-static.loadbalancer.sticky.cookie.name=session
    depends_on:
      - reverse_proxy