version: '3.8'
services:
  reverse_proxy:
    build: .
    container_name: reverse_proxy
    ports:
      - "8080:80"
    environment:
      - WEB_STATIC_HOSTNAME=web_static
      - WEB_DYNAMIC_HOSTNAME=web_dynamic
  web_static:
    build: ../apache-php-image/
    container_name: web_static
    depends_on:
      - reverse_proxy
  web_dynamic:
    build: ../nodejs-image/
    container_name: web_dynamic
    depends_on:
      - reverse_proxy