version: '3.8'
services:
  reverse_proxy:
    image: traefik
    container_name: reverse_proxy
    # Argument supplémentaire utilisé lors du lancement de Traefik
    # Indique à Traefik qu'il s'exécute dans une environnement docker.
    command: --providers.docker
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  web_static:
    build: apache-php-image/
    expose:
      - 80
    labels:
      # Enregistrement du nom d'hôte pour le container 
      - traefik.http.routers.web_static.rule=Host("demo.api.ch")
      # Chemin pour lequel rediriger les requêtes vers le container
      - traefik.http.routers.web-static.rule=PathPrefix("/")
    depends_on:
      - reverse_proxy
  web_dynamic:
    build: nodejs-image/
    expose:
      - 80
    labels:
     - traefik.http.routers.web_dynamic.rule=Host("demo.api.ch")
     - traefik.http.routers.web_dynamic.rule=PathPrefix("/server-info/")
     # Les deux lignes suivantes permettent de ne pas modifier le chemin écouté par le serveur NodeJs.
     - traefik.http.middlewares.web_dynamicPrefix.stripprefix.prefixes=/server-info/
     - traefik.http.routers.web_dynamic.middlewares=web_dynamicPrefix
